---
# tasks file for webapp
- name: Template index.html-ansible_managed.j2 to index.html on target
  template:
    src: index.html-ansible_managed.j2
    dest: "{{ nginx_root_location }}/index.html"
    mode: 0644
  tags:
    - deploy-app
